-- INSERT INTO TBL_USERS (first_name, last_name, email) VALUES
--                                                          ('aaaaaa', 'Kole', 'alex@email.com'),
--                                                          ('Brian', 'Smith', 'brian@email.com'),
--                                                          ('Johnny', 'Wu', 'johnny@email.com');